  with one_across as (
    select one_across."a" as one_across_a, one_across."b" as one_across_b, one_across."c" as one_across_c, one_across."d" as one_across_d, one_across."e" as one_across_e, one_across."f" as one_across_f, one_across."g" as one_across_g, one_across."h" as one_across_h, one_across."i" as one_across_i, one_across."j" as one_across_j, one_across."k" as one_across_k, one_across."l" as one_across_l, one_across."m" as one_across_m, one_across."n" as one_across_n, one_across."o" as one_across_o, one_across."p" as one_across_p, one_across."q" as one_across_q, one_across."r" as one_across_r, one_across."s" as one_across_s, one_across."t" as one_across_t, one_across."u" as one_across_u, one_across."v" as one_across_v, one_across."w" as one_across_w, one_across."x" as one_across_x, one_across."y" as one_across_y from words as one_across
    where one_across_a is not null and one_across_b is not null and one_across_c is not null and one_across_d is not null and one_across_e is not null and one_across_f is null and one_across_g is null and one_across_h is null and one_across_i is null and one_across_j is null and one_across_k is null and one_across_l is null and one_across_m is null and one_across_n is null and one_across_o is null and one_across_p is null and one_across_q is null and one_across_r is null and one_across_s is null and one_across_t is null and one_across_u is null and one_across_v is null and one_across_w is null and one_across_x is null and one_across_y is null
  ), one_down as (
    select one_across.*, one_down."a" as one_down_a, one_down."b" as one_down_b, one_down."c" as one_down_c, one_down."d" as one_down_d, one_down."e" as one_down_e, one_down."f" as one_down_f, one_down."g" as one_down_g, one_down."h" as one_down_h, one_down."i" as one_down_i, one_down."j" as one_down_j, one_down."k" as one_down_k, one_down."l" as one_down_l, one_down."m" as one_down_m, one_down."n" as one_down_n, one_down."o" as one_down_o, one_down."p" as one_down_p, one_down."q" as one_down_q, one_down."r" as one_down_r, one_down."s" as one_down_s, one_down."t" as one_down_t, one_down."u" as one_down_u, one_down."v" as one_down_v, one_down."w" as one_down_w, one_down."x" as one_down_x, one_down."y" as one_down_y from words as one_down
    join one_across on one_across_a = one_down_a
    where one_down_a is not null and one_down_b is null and one_down_c is null and one_down_d is null and one_down_e is null and one_down_f is not null and one_down_g is null and one_down_h is null and one_down_i is null and one_down_j is null and one_down_k is not null and one_down_l is null and one_down_m is null and one_down_n is null and one_down_o is null and one_down_p is null and one_down_q is null and one_down_r is null and one_down_s is null and one_down_t is null and one_down_u is null and one_down_v is null and one_down_w is null and one_down_x is null and one_down_y is null
  ), two_down as (
    select one_down.*, two_down."a" as two_down_a, two_down."b" as two_down_b, two_down."c" as two_down_c, two_down."d" as two_down_d, two_down."e" as two_down_e, two_down."f" as two_down_f, two_down."g" as two_down_g, two_down."h" as two_down_h, two_down."i" as two_down_i, two_down."j" as two_down_j, two_down."k" as two_down_k, two_down."l" as two_down_l, two_down."m" as two_down_m, two_down."n" as two_down_n, two_down."o" as two_down_o, two_down."p" as two_down_p, two_down."q" as two_down_q, two_down."r" as two_down_r, two_down."s" as two_down_s, two_down."t" as two_down_t, two_down."u" as two_down_u, two_down."v" as two_down_v, two_down."w" as two_down_w, two_down."x" as two_down_x, two_down."y" as two_down_y from words as two_down
    join one_down on one_down_c = two_down_c
    where two_down_a is null and two_down_b is null and two_down_c is not null and two_down_d is null and two_down_e is null and two_down_f is null and two_down_g is null and two_down_h is not null and two_down_i is null and two_down_j is null and two_down_k is null and two_down_l is null and two_down_m is not null and two_down_n is null and two_down_o is null and two_down_p is null and two_down_q is null and two_down_r is not null and two_down_s is null and two_down_t is null and two_down_u is null and two_down_v is null and two_down_w is not null and two_down_x is null and two_down_y is null
  )
  select one_down.*, two_down.*
  from words as two_down
  join one_down on one_down_c = two_down.c
  limit 1
